### ISSUE TITLE
use of historical data

### ISSUE THREAD

**Issue by olexiyb** [GuntharDeNiro/BTCT#1]
Hey, according to 
https://gunthy.org/index.php?topic=193.0

Gunbot only sees data it has collected itself. When it makes a call to the exchange, it is pulling whatever the newest price is at it existed on the books at that time. It logs this in memory and in the logs. How accurate this data is will be highly dependent on how often you are asking for the pricing data.

This looks very inefficient, why not use an approach like this to get historical data?

https://github.com/jyunfan/poloniex-data/blob/master/getdata.py

**Comment by aluhme** [comment]
You have no clue what you talking about: we already get those so called "historical data"
EMA and Bollinger Band are NOT in those data and everyone (included the guy you mentioned) must collect it by himself

**Comment by olexiyb** [comment]
I have copy/pasted information from provided link, please follow it. This is not my statement above!

**Comment by GuntharDeNiro** [comment]
Gunbot uses historical data from poloniex and all other exchanges since it was born. Unfortunately Poloniex and other exchanges doesnt send us indicators like Bollinger Band, ema: so we need to calculate them by ourselves like all other bots do.
Another question i was asked if the bot can change settings on the fly: of course yes, since first commit of 2.x version.
Hope it helped.
~Gun

**Comment by utdrmac** [comment]
@olexiyb You good? Can you close this issue?
