### ISSUE TITLE
stop_limit not working properly

### ISSUE THREAD

**Issue by dotpim** [GuntharDeNiro/BTCT#136]
Stop_limit is not selling of assets consistently for me. Sometimes it does, sometimes it does not.

Currently running stepgain with:
"STOP_LIMIT": 15,

I would expect gunbot to sell when the current price drops >15% of the bought price. This did not happen recently on Poloniex.

Bought SYS at 0.00005201, current price for SYS is 0.00004362 (>16% lower). No sell order has been placed.

On Bittrex i did have some cases where assets were sold after the limit was reached.

**Comment by strongboy54** [comment]
Check the logs on gunbot for how often it checks if it should sell that pair. I'm experiencing a similar issue but I believe it's due to an error with how often it checks the pair's price rather than the stop limit not working.

And by check logs I mean create a log file, capture logs for a while and go through that file to see how often each pair's price is checked.

**Comment by dotpim** [comment]
SYS is being checked about every minute. With each recent check returning a price that's below the point where it should have sold.

Relevant recent log entries:
2017/09/21 16:13:19: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:13:22: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042543/0.00005284216
2017/09/21 16:15:21: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:15:27: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042533219999999996/0.00005284216
2017/09/21 16:16:38: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:16:41: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042533219999999996/0.00005284216
2017/09/21 16:17:19: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:17:21: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042533219999999996/0.00005284216
2017/09/21 16:17:46: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:17:50: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042533219999999996/0.00005284216
2017/09/21 16:19:08: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:19:10: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042572339999999995/0.00005284216
2017/09/21 16:20:21: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:20:23: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.0000425919/0.00005284216
2017/09/21 16:21:17: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:21:19: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.00004260168/0.00005284216
2017/09/21 16:22:33: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:22:36: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042611459999999994/0.00005284216
2017/09/21 16:23:21: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:23:23: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042611459999999994/0.00005284216
2017/09/21 16:23:33: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:23:34: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042611459999999994/0.00005284216
2017/09/21 16:24:43: BTC_SYS Last Bid/Ask 0.00004362/0.00004363
2017/09/21 16:24:46: Trend for BTC_SYS:    UP!!!
Nothing changed in BTC_SYS: Bid/Ask is 0.00004362/0.00004363. Entry points are: 0.000042611459999999994/0.00005284216

**Comment by strongboy54** [comment]
Last Bid/Ask 0.00004362/0.00004363
Entry points 0.000042611459999999994/0.00005284216

I don't get it. The bid/ask price is not below stop loss.

**Comment by dotpim** [comment]
Bought price is: 0.00005201
15% loss from that equals: 0.00004420

Current bid/ask prices are all below 0.00004420 --> Why is it not selling? Or at what point is my logic failing?

**Comment by strongboy54** [comment]
To not spam this with just "chat". Sorry, I was a bit slow to realise it fully. Your logic is not failing. The stop loss for some reason has not been set correctly. It's scheduled to sell at 0.000042611 when it should be scheduled to sell at 0.00004420.

**Comment by paramecie** [comment]
Hi - 
Yes, 4420 is the correct value for -15%.
But depends how GB calculates "the stop-limit price".
Is is Bid? Ask? An average? SMA? That may be the problem.

**Comment by GuntharDeNiro** [comment]
@paramecie by the bought price of course

**Comment by paramecie** [comment]
Yes, of course. I was trying to see if there could be a bias here.

BTW, while you're here:
* estimate of 5.0.5 release, because 3.3.2 is a pure pain :-(
* please describe BOT_DELAY=1, I lost hours to make tests, not even sure of the measure (s, ms?) and how/when it's applied. THANK YOU.

**Comment by GuntharDeNiro** [comment]
@paramecie i'm not here, i'm on telgram, this is an issue tracker

**Comment by paramecie** [comment]
Sorry, I started with my programs saved on perforated paper ribbons. Don't know Telegram. OK, I decided to try this. Thanks for everything.

**Comment by dotpim** [comment]
Update: in the end Stop_Limit kicked in for this pair. But at an unexpected %.

Sell order placed for 0.00004231 = -18,7% instead of configured-15%.
Not acceptable IMO.

**Comment by tandyuk** [comment]
Ive just haad an issue where the bot sold, due to hitting stop limit, instantly rebought, then instantly resold at the same price due to hitting the previous stop limit.

Fortunately I saw the order come up and cancelled it, but basically the bot didnt see the bought_price update fast enough.


71|b_BTC-S | Loading config...
71|b_BTC-S | Loading exchange bittrex
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S |  ɢՍΠɃ۝Ł v5.0.4  Scanning bittrex for trading opportunities 2017/09/28 01:22:06
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:07: BTC-SYNX Last Bid/Ask 0.00005744/0.00005750
71|b_BTC-S | 2017/09/28 01:22:07: Got Trading History
71|b_BTC-S | 2017/09/28 01:22:07: Averaged bought price: 0.0000698
71|b_BTC-S | 2017/09/28 01:22:07: Price to sell: 0.00007042820000000001
71|b_BTC-S | 2017/09/28 01:22:07: EMA1: 0.00005993/EMA2: 0.00006001
71|b_BTC-S | 2017/09/28 01:22:07: Price to buy: 0.00005897
71|b_BTC-S | 2017/09/28 01:22:08: Got Open Orders
71|b_BTC-S | 2017/09/28 01:22:08: Last Bid/Price to sell: 0.00005744/0.00007043
71|b_BTC-S | 2017/09/28 01:22:08: Last Ask/Price to buy: 0.00005750/0.00005897
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | EMA1: 0.00005993 == EMA2: 0.00006001
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:08: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | 2017/09/28 01:22:08: We are on level 1 to sell (bought/sell at): 0.0000698/0.00007042820000000001
71|b_BTC-S |  ɢƱŋβʘŁ v5.0.4  Tips&Tricks: BTC-SYNX can be bought, checking balances...
71|b_BTC-S | 2017/09/28 01:22:08: There are some trading opportunities for BTC-SYNX at bittrex. Scanning Trade History
71|b_BTC-S | 2017/09/28 01:22:08: Last Bid price BTC-SYNX: 0.00005744 | Last Ask: 0.0000575
71|b_BTC-S | 2017/09/28 01:22:08: Balance BTC: 0.04996666
71|b_BTC-S | 2017/09/28 01:22:08: Balance SYNX: 716.33237822
71|b_BTC-S | 2017/09/28 01:22:08: On Orders SYNX: 0
71|b_BTC-S | 2017/09/28 01:22:08: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | Processing strategy STEPGAIN for BTC-SYNX on bittrex
71|b_BTC-S | 2017/09/28 01:22:08: To sell we need 0.000102865329512392 BTC for fees - We have: 0.04996666 BTC
71|b_BTC-S | ┌───────────────┬────────────┬────────────┬────────────┬──────────────┬───────────┬──────────┐
71|b_BTC-S | │ ɢՍΠɃøͳ v5.0.4 │ EMA1       │ EMA2       │ Last       │ SYNX         │ Last Buy  │ Pair     │
71|b_BTC-S | ├───────────────┼────────────┼────────────┼────────────┼──────────────┼───────────┼──────────┤
71|b_BTC-S | │ Sell cycle    │ 0.00005993 │ 0.00006001 │ 0.00005744 │ 716.33237822 │ 0.0000698 │ BTC-SYNX │
71|b_BTC-S | └───────────────┴────────────┴────────────┴────────────┴──────────────┴───────────┴──────────┘
71|b_BTC-S | ************************************************************************************************
71|b_BTC-S | Strategy STEPGAIN for BTC-SYNX on bittrex -| Selling 716.33237822 of BTC-SYNX at rate 0.00005744
71|b_BTC-S | ************************************************************************************************
71|b_BTC-S | STOP LIMIT REACHED!!! SELLING ALL YOUR ASSETS!!!!
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S |  ɢƱŋƁѺͳ v5.0.4  Scanning bittrex for trading opportunities 2017/09/28 01:22:14
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:14: BTC-SYNX Last Bid/Ask 0.00005744/0.00005750
71|b_BTC-S | 2017/09/28 01:22:15: Got Trading History
71|b_BTC-S | 2017/09/28 01:22:15: Averaged bought price: 0.0000698
71|b_BTC-S | 2017/09/28 01:22:15: Price to sell: 0.00007042820000000001
71|b_BTC-S | 2017/09/28 01:22:15: EMA1: 0.00005973/EMA2: 0.00005971
71|b_BTC-S | 2017/09/28 01:22:15: Price to buy: 0.00005875
71|b_BTC-S | 2017/09/28 01:22:16: Got Open Orders
71|b_BTC-S | 2017/09/28 01:22:16: Last Bid/Price to sell: 0.00005744/0.00007043
71|b_BTC-S | 2017/09/28 01:22:16: Last Ask/Price to buy: 0.00005750/0.00005875
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | EMA1: 0.00005973 == EMA2: 0.00005971
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:16: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | 2017/09/28 01:22:16: We are on level 1 to sell (bought/sell at): 0.0000698/0.00007042820000000001
71|b_BTC-S |  ɢՍŋßʘŁ v5.0.4  Tips&Tricks: BTC-SYNX can be bought, checking balances...
71|b_BTC-S | 2017/09/28 01:22:16: There are some trading opportunities for BTC-SYNX at bittrex. Scanning Trade History
71|b_BTC-S | 2017/09/28 01:22:16: Last Bid price BTC-SYNX: 0.00005744 | Last Ask: 0.0000575
71|b_BTC-S | 2017/09/28 01:22:16: Balance BTC: 0.09100993
71|b_BTC-S | 2017/09/28 01:22:16: Balance SYNX: 0
71|b_BTC-S | 2017/09/28 01:22:16: On Orders SYNX: 0
71|b_BTC-S | 2017/09/28 01:22:16: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | Processing strategy STEPGAIN for BTC-SYNX on bittrex
71|b_BTC-S | ┌───────────────┬─────────────┬──────────────┬─────────────────────────┬───────────┬────────────┬──────┬──────────┐
71|b_BTC-S | │ ɢՍÑβ๏ͳ v5.0.4 │ EMA1        │ EMA2         │ Buy at                  │ Last      │ BTC        │ SYNX │ Pair     │
71|b_BTC-S | ├───────────────┼─────────────┼──────────────┼─────────────────────────┼───────────┼────────────┼──────┼──────────┤
71|b_BTC-S | │ Buy cycle     │ 0.00005973  │ 0.00005971   │ 0.000058754640000000004 │ 0.0000575 │ 0.09100993 │ 0    │ BTC-SYNX │
71|b_BTC-S | ├───────────────┼─────────────┼──────────────┼─────────────────────────┼───────────┼────────────┼──────┼──────────┤
71|b_BTC-S | │ Callbacks     │ Time to buy │ 0.0000575    │ BTC-SYNX                │           │            │      │          │
71|b_BTC-S | ├───────────────┼─────────────┼──────────────┼─────────────────────────┼───────────┼────────────┴──────┴──────────┤
71|b_BTC-S | │ BOUGHT!!!     │ Amount:     │ 695.65217391 │ Rate:                   │ 0.0000575 │                              │
71|b_BTC-S | └───────────────┴─────────────┴──────────────┴─────────────────────────┴───────────┴──────────────────────────────┘
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S |  ɢՍͶβøŁ v5.0.4  Scanning bittrex for trading opportunities 2017/09/28 01:22:35
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:36: BTC-SYNX Last Bid/Ask 0.00005750/0.00005751
71|b_BTC-S | 2017/09/28 01:22:36: Got Trading History
71|b_BTC-S | 2017/09/28 01:22:36: Averaged bought price: 0.0000698
71|b_BTC-S | 2017/09/28 01:22:36: Price to sell: 0.00007042820000000001
71|b_BTC-S | 2017/09/28 01:22:36: EMA1: 0.00005973/EMA2: 0.00005971
71|b_BTC-S | 2017/09/28 01:22:36: Price to buy: 0.00005875
71|b_BTC-S | 2017/09/28 01:22:37: Got Open Orders
71|b_BTC-S | 2017/09/28 01:22:37: Last Bid/Price to sell: 0.00005750/0.00007043
71|b_BTC-S | 2017/09/28 01:22:37: Last Ask/Price to buy: 0.00005751/0.00005875
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | EMA1: 0.00005973 == EMA2: 0.00005971
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:37: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | 2017/09/28 01:22:37: We are on level 1 to sell (bought/sell at): 0.0000698/0.00007042820000000001
71|b_BTC-S |  ɢƱƝɃǾͳ v5.0.4  Tips&Tricks: BTC-SYNX can be bought, checking balances...
71|b_BTC-S | 2017/09/28 01:22:37: There are some trading opportunities for BTC-SYNX at bittrex. Scanning Trade History
71|b_BTC-S | 2017/09/28 01:22:37: Last Bid price BTC-SYNX: 0.0000575 | Last Ask: 0.00005751
71|b_BTC-S | 2017/09/28 01:22:37: Balance BTC: 0.05090995
71|b_BTC-S | 2017/09/28 01:22:37: Balance SYNX: 353.21313673
71|b_BTC-S | 2017/09/28 01:22:37: On Orders SYNX: 0
71|b_BTC-S | 2017/09/28 01:22:37: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | Processing strategy STEPGAIN for BTC-SYNX on bittrex
71|b_BTC-S | 2017/09/28 01:22:37: To sell we need 0.000050774388404937504 BTC for fees - We have: 0.05090995 BTC
71|b_BTC-S | ┌───────────────┬────────────┬────────────┬───────────┬──────────────┬───────────┬──────────┐
71|b_BTC-S | │ ɢՍÑɃ۝ͳ v5.0.4 │ EMA1       │ EMA2       │ Last      │ SYNX         │ Last Buy  │ Pair     │
71|b_BTC-S | ├───────────────┼────────────┼────────────┼───────────┼──────────────┼───────────┼──────────┤
71|b_BTC-S | │ Sell cycle    │ 0.00005973 │ 0.00005971 │ 0.0000575 │ 353.21313673 │ 0.0000698 │ BTC-SYNX │
71|b_BTC-S | └───────────────┴────────────┴────────────┴───────────┴──────────────┴───────────┴──────────┘
71|b_BTC-S | ************************************************************************************************
71|b_BTC-S | Strategy STEPGAIN for BTC-SYNX on bittrex -| Selling 353.21313673 of BTC-SYNX at rate 0.0000575
71|b_BTC-S | ************************************************************************************************
71|b_BTC-S | STOP LIMIT REACHED!!! SELLING ALL YOUR ASSETS!!!!
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S |  ɢƱƝɮ๏Ŧ v5.0.4  Scanning bittrex for trading opportunities 2017/09/28 01:22:57
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:57: BTC-SYNX Last Bid/Ask 0.00005744/0.00005750
71|b_BTC-S | 2017/09/28 01:22:58: Got Trading History
71|b_BTC-S | 2017/09/28 01:22:58: Averaged bought price: 0.0000575
71|b_BTC-S | 2017/09/28 01:22:58: Price to sell: 0.000058017500000000005
71|b_BTC-S | 2017/09/28 01:22:58: EMA1: 0.00005991/EMA2: 0.00005988
71|b_BTC-S | 2017/09/28 01:22:58: Price to buy: 0.00005892
71|b_BTC-S | 2017/09/28 01:22:59: Got Open Orders
71|b_BTC-S | 2017/09/28 01:22:59: Last Bid/Price to sell: 0.00005744/0.00005802
71|b_BTC-S | 2017/09/28 01:22:59: Last Ask/Price to buy: 0.00005750/0.00005892
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | EMA1: 0.00005991 == EMA2: 0.00005988
71|b_BTC-S | ------------------------------------------------------------------------------------------------
71|b_BTC-S | 2017/09/28 01:22:59: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | 2017/09/28 01:22:59: We are on level 1 to sell (bought/sell at): 0.0000575/0.000058017500000000005
71|b_BTC-S |  ɢՍÑɮøŦ v5.0.4  Tips&Tricks: BTC-SYNX can be bought, checking balances...
71|b_BTC-S | 2017/09/28 01:22:59: There are some trading opportunities for BTC-SYNX at bittrex. Scanning Trade History
71|b_BTC-S | 2017/09/28 01:22:59: Last Bid price BTC-SYNX: 0.00005744 | Last Ask: 0.0000575
71|b_BTC-S | 2017/09/28 01:22:59: Balance BTC: 0.07055098
71|b_BTC-S | 2017/09/28 01:22:59: Balance SYNX: 342.43903718
71|b_BTC-S | 2017/09/28 01:22:59: On Orders SYNX: 10.7741
71|b_BTC-S | 2017/09/28 01:22:59: Trend for BTC-SYNX:    UP!!!
71|b_BTC-S | Processing strategy STEPGAIN for BTC-SYNX on bittrex
71|b_BTC-S | ┌─────────────────┬─────────────────────┬─────────────────────────┬──────────┬──┐
71|b_BTC-S | │ ɢƱҊɃ۝Ł v5.0.4   │ EMA1                │ EMA2                    │ Pair     │  │
71|b_BTC-S | ├─────────────────┼─────────────────────┼─────────────────────────┼──────────┤  │
71|b_BTC-S | │ Sell cycle      │ 0.00005991          │                         │ BTC-SYNX │  │
71|b_BTC-S | ├─────────────────┼─────────────────────┼─────────────────────────┼──────────┼──┤
71|b_BTC-S | │ GUNBOT CALLBACK │ 2017/09/28 01:22:59 │ Waiting for open orders │          │  │
71|b_BTC-S | └─────────────────┴─────────────────────┴─────────────────────────┴──────────┴──┘
