### ISSUE TITLE
[kraken] -| Error: FUCK KRAKEN

### ISSUE THREAD

**Issue by miwi-fbsd** [GuntharDeNiro/BTCT#172]
Hi,

We have been playing the bot on kraken and hit once in the while the following error:

Error on strategy STEPGAIN for ETCUSD on kraken while getting order book -| Error: FUCK KRAKEN

I am using in this example diesel's stepgain config, but it dosent matter because the error is also with any other strategy. Also the bot is ***** slow compare to the bittrex instance

Tested on 5.0.4 and 5.0.5.5

As well we have recorded to 2 small vids on 2 different vm's first located in Singapore, sec located in the US close to kraken.

1)
https://asciinema.org/a/UegNKiUymzTiKj2jXliS2bFrP 
2)
https://asciinema.org/a/54TEbiQfjXHUZ9qmWqMroB06Y

Does anyone have an idea on how to solve those both problems?

Thanks

**Comment by paramecie** [comment]
The fuck kraken may be caused by their own incapacity to provide a reliable service:

https://status.kraken.com
- for months in "degraded performance"...

Gunthy can't wait 1, 2 or 5 seconds to get a query result, as the total pairs cycle delay would be multiplied by 10,20 or more times.

My guess...
