### ISSUE TITLE
(XT) Use config.js values even when using the UI

### ISSUE THREAD

**Issue by nomad5am** [GuntharDeNiro/BTCT#179]
Iy would be great to override the database settings and use the config.js only, but still be able to use and watch the UI. maybe this can be added as a bot setting attribute?

**Comment by equalgeek** [comment]
This would be nice, mainly because that way we can manually edit the pairs and the strategy for each pair quicker than in the gui. Right now it is kinda cumbersome to change the strategy for each pair clicking on each tab to change it and then also making sure to click update at the bottom of the page. It is fine for changing a single pair to a different strat, but changing 20 or so pairs to a different strat takes some time. One thing I was thinking is that there could be sub tabs inside the main tab. One for the config and then one for the TV. Idk, just throwing something out there.. Although I just have to say this is definitely by far the best version so far. Thanks to everyone for their hard work.

**Comment by smportis** [comment]
I agree that it would be nice to be able to edit multiple coins at once to change settings (like to change from stepgain to bb etc). Perhaps this can be added in the gui to click the check box by multiple coins and then change an attribute for all those coins. 

However, I thought that editing the config file and then reloading that file via import DID work. Does it not?

**Comment by dotpim** [comment]
Closing this as importing from config.js already works fine.

Using GUI while syncing with config.js might be built into a later release.
