### ISSUE TITLE
4.0.1 on Bittrex hanging

### ISSUE THREAD

**Issue by jadiesel** [GuntharDeNiro/BTCT#27]
On Polo, the bot will stop log output for upwards of 8 minutes at a time (20 pairs). Mostly it sems to slow down over time, so that a restart will see a flurry of activity, then over the next few minutes, the outout will get slower and slower.   This may be fine.

BUT, the Bittrex bot is processing for 1 to 2 minutes (actually went 5 minutes once), then it stops. No log output, and np CPU usage. I haven't let it go longer than 40 minutes.  I did set up a cron  that reloads it (pm2) every minute... it seems to run ok, and has made some trades after that.  Seems like a nasty kludge though.

I have tried this on two different VPS servers (Contabo and Westhost), and the results were identical.
I also tried running bittrex and polo together on one bot, but had the same results, bittrex just stopped outputting and never picked back up again.

**Comment by bigwest60** [comment]
I am experiencing the same (hanging on Bittrex after a couple minutes).  I am running on a Raspberry Pi running Raspbian.

**Comment by Jverse** [comment]
Same here been testing for an hour

On Aug 10, 2017 11:27 PM, "Bill Cropper" <notifications@github.com> wrote:

I am experiencing the same (hanging on Bittrex after a couple minutes). I
am running on a Raspberry Pi running Raspbian.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GuntharDeNiro/BTCT/issues/27#issuecomment-321729788>,
or mute the thread

**Comment by mikebussy3334** [comment]
Me too.

**Comment by lupeto77** [comment]
me too on bittrex

**Comment by nlegall** [comment]
Same it just stops

**Comment by mikebussy3334** [comment]
The update did nothing, Bittrex still hangs.
