### ISSUE TITLE
Gunbot should NEVER sell for a loss

### ISSUE THREAD

**Issue by uygaronur** [GuntharDeNiro/BTCT#277]
I was running Gunbot with default BBRSI settings, except RSI_BUY_LEVEL was set to 28. It sold all my ETC and some XEM for a hefty loss. 

I think Gunbot should never sell if the proceeds wouldn't cover the expenses. We shouldn't have to check every trade to see if we're at a loss. The last step before Gunbot places any sell order should be checking if the order is profitable. Otherwise I cannot have any peace of mind while the bot is running.

We can never be 100% sure if it's a good time to buy but we can be sure if it's OK to sell (profitable). Get the buying price, add the fees and you'd have the minimum price to sell.

**Comment by cryptowally** [comment]
I think gunbot already does this - at least it used to, with some simple math, unless SECURITY_MARGIN (now called STOP_LOSS) was invoked... where:

**boughtPrice** is known by gunbot, because it either looked it up in the order history via API or it bought it itself and stored it in the .json files.  (in different versions it probably has behaved differently).  But let's say it at least has a boughtPrice that is accurate for now 

gunbot sets a **prSell** (price to sell) and then, as we all know, waits and waits to sell the coin.  It monitors the price and gets **LP** (last price) and waits until it meets or exceeds **prSell**.  

When the current price DOES meet or exceed **prSell**, it doesn't necessarily immediately sell the coin because HEY! the coin's price might still be rising like a rocket.  You wouldn't necessarily want gunbot to miss out on that rocket and sell too early.  

This is where all the parameters to tweak gunbot come in.  It's very difficult to predict when gunbot is supposed to sell vs wait.  However, the issue here is whether gunbot sells at a loss.  

No matter what gunbot is doing during it's decision to sell, at some point, gunbot makes a decision to sell.  There is then the CALLBACK to exchange to actually send the API call.  

This is where there should be the last minute "safety check" that whatever the "limit sell" price is that is being sent to the exchange should be greater than or equal to the **boughtPrice**

I'd ask the developers to go further and add a user-configurable option, both global and per-coin, that is "backstop" or "minprofit" or "tradingfee" or however you want to call it.   This would be a percentage that the exchange uses as a fee and is seen as overhead and is taken out as profit, so gunbot should be considering that as a "cost" and should NOT sell a coin unless the prSell is at least boughtPrice + this value 

Example:

- boughtPrice = 0.001
- tradingfee = 0.25 (standard bittrex commission of 0.25 percent)
- no matter what sell strategy is used, if gunbot is going along, gunbot will never issue a limit sell order less than 0.0010025, which is 0.25% higher than boughtPrice
- if for some reason, it gets to the point and it tries to place an order that is lower than boughtPrice * (1+tradingfee), it should display a message "resulting order would not cover configured tradingfee of 0.25%" 

This should prevent trading at a loss and allow the user to supply their own user-configured trading fees per exchange and per coin pair.

**Comment by GuntharDeNiro** [comment]
making bbrsi strategy to look at GAIN kills the strategy itself.
