### ISSUE TITLE
6.0.3_beta: Bitfinex not buying. Empty callbacks.

### ISSUE THREAD

**Issue by ketonatus** [GuntharDeNiro/BTCT#286]
Have several strats running, but only **bbrsistepgain** and **tsslgain** are showing a try to buy.

GBXT_v6.0.3_beta OMG-BTC Round # 3
 ɢՍÑɮѺŁ XT Edition  Scanning bitfinex for trading opportunities 2017/12/04 10:16:24
2017/12/04 10:16:25: OMG-BTC Last Bid/Ask 0.00083000/0.00083009
EMA1: 0.0008339138478507464 === EMA2: 0.0008339586471311021
HIGH BB: 0.00084290 == SMA: 0.00083535 == LOW BB: 0.00082781
2017/12/04 10:16:28: Got Trading History
2017/12/04 10:16:28: Checking Open Orders
2017/12/04 10:16:28: TrailingBuy limit 0.00082815
2017/12/04 10:16:28: Last price         0.00083009   |  Target to buy:   0.00083308
2017/12/04 10:16:28: Stop limit     0.00083315000
2017/12/04 10:16:28: Price of           OMG-BTC is going  UP 
2017/12/04 10:16:28: Moving TrailingBuy limit to 0.00082511
2017/12/04 10:16:28: Stop limit is   0.00083315000
2017/12/04 10:16:28: Price to buy: 0.00083308
2017/12/04 10:16:28: Last Bid/Strategy Exit Point: 0.00083000/0.0008580444000000001
2017/12/04 10:16:28: Last Ask/Strategy Entry Point: 0.00083009/0.00083308
2017/12/04 10:16:28: There are some trading opportunities for OMG-BTC at bitfinex. Scanning Trade History
 ɢƱŋɮםŦ XT Edition  Tips&Tricks: OMG-BTC can be bought!!! 
2017/12/04 10:16:28: Last Bid price OMG-BTC: 0.00083 | Last Ask: 0.00083009
2017/12/04 10:16:28: Balance BTC: 0.01060499
2017/12/04 10:16:28: Balance OMG: 0.0
2017/12/04 10:16:28: On Orders OMG: 0
Processing strategy tsslgain for OMG-BTC on bitfinex
2017/12/04 10:16:28: Entering buy cycle
┌───────────────────┬───────┬────────┬────────┬──────┬────────────┬─────┬─────────┐
│ ɢՍÑƁםͳ XT Edition │ LowBB │ HighBB │ Buy at │ Last │ BTC        │ OMG │ Pair    │
├───────────────────┼───────┼────────┼────────┼──────┼────────────┼─────┼─────────┤
│ Buy cycle         │       │        │        │      │ 0.01060499 │     │ OMG-BTC │
├───────────────────┼───────┼────────┴────────┴──────┴────────────┴─────┴─────────┤
│ Callbacks         │       │                                                     │
└───────────────────┴───────┴─────────────────────────────────────────────────────┘

//

GBXT_v6.0.3_beta LTC-BTC Round # 12
ɢƱŋßØŁ XT Edition  Scanning bitfinex for trading opportunities 2017/12/04 10:27:53
2017/12/04 10:27:54: LTC-BTC Last Bid/Ask 0.00874000/0.00875190
EMA1: 0.008710861668862516 === EMA2: 0.008719366543876826
HIGH BB: 0.00902678 == SMA: 0.00880758 == LOW BB: 0.00858839
RSI: 48.08927418994725

2017/12/04 10:28:01: Got Trading History
2017/12/04 10:28:01: Checking Open Orders
2017/12/04 10:28:01: Price to buy: 0.008803200037959348
2017/12/04 10:28:01: Last Bid/Strategy Exit Point: 0.00874000/0.009237732
2017/12/04 10:28:01: Last Ask/Strategy Entry Point: 0.00875190/0.008803200037959348
2017/12/04 10:28:01: XTrend for LTC-BTC:    UP!!!   
2017/12/04 10:28:01: There are some trading opportunities for LTC-BTC at bitfinex. Scanning Trade History
 ɢƱÑɃǾŦ XT Edition  Tips&Tricks: LTC-BTC can be bought!!! 
2017/12/04 10:28:01: Last Bid price LTC-BTC: 0.00874 | Last Ask: 0.0087519
2017/12/04 10:28:01: Balance BTC: 0.01060499
2017/12/04 10:28:01: Balance LTC: 0.0
2017/12/04 10:28:01: On Orders LTC: 0
Processing strategy bbrsistepgain for LTC-BTC on bitfinex
2017/12/04 10:28:01: Entering buy cycle
┌───────────────────┬───────┬────────┬────────┬──────┬────────────┬─────┬─────────┐
│ ɢՍΠɮØŁ XT Edition │ LowBB │ HighBB │ Buy at │ Last │ BTC        │ LTC │ Pair    │
├───────────────────┼───────┼────────┼────────┼──────┼────────────┼─────┼─────────┤
│ Buy cycle         │       │        │        │      │ 0.01060499 │     │ LTC-BTC │
├───────────────────┼───────┼────────┴────────┴──────┴────────────┴─────┴─────────┤
│ Callbacks         │       │                                                     │
└───────────────────┴───────┴─────────────────────────────────────────────────────┘

**// config TSSLGAIN**
     "tsslgain": {
            "NAME": "tsslgain",
            "TRADING_LIMIT": 0.001,
            "PERIOD": 15,
            "BUY_RANGE": 0.6,
            "BUY_LEVEL": 0.1,
            "GAIN": 2,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 49,
            "LOW_BB": 49,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "TSSL_TARGET_ONLY": true,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
	    "OKKIES_MODE": true,
	    "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 60
        },

**// config bbrsistepgain**
       "bbrsistepgain": {
            "NAME": "bbrsistepgain",
            "TRADING_LIMIT": 0.001,
            "PERIOD": 15,
            "RSI_BUY_LEVEL": 30,
            "GAIN":2,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 49,
            "LOW_BB": 49,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SELLLVL1": 0.6,
            "SELLLVL2": 2,
            "SELLLVL3": 70,
            "SELLLVL": 2,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
	    "OKKIES_MODE": true,
	    "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 60
        },

**Comment by c64audio** [comment]
I have a similar problem with 6.0.2 on bbstepgain. I tried turning off okkies_mode (because that can suppress buys without leaving a message) but the behavour is unchanged. I've run it on Windows and Linux, with exactly the same behaviour. 

So after I turned the bot on, it bought for five minutes, then stopped buying and sold over a few hours, while doing the same with with buy requests as here: wanting to do it, but not.

The transactions from Bittrex here show what happened from when I switched the bot on for the first time to now. As you can see, the non-buying started during the run (after the safety switch period), but is not due to cloudflare problems (which would have resulted in all traffic being blocked, not just buys).  There were no errors during the run.

CLOSED DATE   OPENED DATE   MARKET   TYPE   BID/ASK   UNITS FILLED   UNITS TOTAL   ACTUAL RATE   COST / PROCEEDS
12/14/2017 04:08:14 AM   12/14/2017 04:08:14 AM   BTC-XEM   Limit Sell   0.00003240   31.70577045   31.70577045   0.00003239   0.00102470
12/14/2017 01:33:49 AM   12/14/2017 01:33:49 AM   BTC-DASH   Limit Sell   0.05380000   0.01879874   0.01879874   0.05379988   0.00100885
12/13/2017 11:37:59 PM   12/13/2017 11:36:30 PM   BTC-ETC   Limit Sell   0.00181830   0.55558642   0.55558642   0.00181829   0.00100770
12/13/2017 10:43:01 PM   12/13/2017 10:43:01 PM   BTC-ARDR   Limit Sell   0.00005934   17.21466689   17.21466689   0.00005933   0.00101896
12/13/2017 10:09:09 PM   12/13/2017 10:09:09 PM   BTC-EDG   Limit Sell   0.00008450   12.12121212   12.12121212   0.00008449   0.00102168
12/13/2017 09:51:06 PM   12/13/2017 09:48:58 PM   BTC-EDG   Limit Buy   0.00008250   12.12121212   12.12121212   0.00008249   -0.00100248
12/13/2017 09:48:50 PM   12/13/2017 09:48:50 PM   BTC-XEM   Limit Buy   0.00003154   31.70577045   31.70577045   0.00003153   -0.00100248
12/13/2017 09:48:41 PM   12/13/2017 09:48:41 PM   BTC-WAVES   Limit Buy   0.00083600   1.19617224   1.19617224   0.00083498   -0.00100128
12/13/2017 09:47:58 PM   12/13/2017 09:47:58 PM   BTC-ARDR   Limit Buy   0.00005809   17.21466689   17.21466689   0.00005808   -0.00100248
12/13/2017 09:46:42 PM   12/13/2017 09:46:42 PM   BTC-DASH   Limit Buy   0.05319505   0.01879874   0.01879874   0.05319452   -0.00100248
12/13/2017 09:46:33 PM   12/13/2017 09:46:33 PM   BTC-ETC   Limit Buy   0.00179990   0.55558642   0.55558642   0.00179988   -0.00100248

        "bbstepgain": {
            "NAME": "bbstepgain",
            "TRADING_LIMIT": 0.0001,
            "PERIOD": 15,
            "BUY_LEVEL": 0.2,
            "GAIN": 1,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 40,
            "LOW_BB": 30,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SELLLVL1": 1,
            "SELLLVL2": 5,
            "SELLLVL3": 70,
            "SELLLVL": 1,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 50,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 300
        },

"pairs": {
        "bittrex": {
            "BTC-ETH": {
                "strategy": "bbstepgain",
                "override": {
                    "HIGH_BB": 40,
                    "LOW_BB": 30
                }
            },
            "BTC-BCC": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-BTG": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-ETC": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-DASH": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-EMC2": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-KMD": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-1ST": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-RISE": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-UBQ": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-MCO": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-NXS": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-CVC": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-ARDR": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-SIB": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-BAT": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-DCR": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-WAVES": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-XEM": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-EDG": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-PAY": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-DGB": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-ZEC": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-ADA": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-NEO": {
                "strategy": "bbstepgain",
                "override": {}
            },
            "BTC-XMR": {
                "strategy": "stepgain",
                "override": {}
            },
            "BTC-XRP": {
                "strategy": "stepgain",
                "override": {}
            }
        }
