### ISSUE TITLE
Blank black screen pop up every other second

### ISSUE THREAD

**Issue by rbish** [GuntharDeNiro/BTCT#340]
When I run 7.2 version every second black blank screen flashes on screen on and off consistently.

**Comment by sloaleks** [comment]
wiki :
Console screen flashes repeatedly after starting a setup. Gunbot does not start running.
Often accompanied by the following error message: Error: read ECONNRESET

This happens when Gunbot cannot be started correctly.

Common solution:

Add rules to your local firewall to accept incoming and outgoing traffic on port 5000.
When you run multiple instances: make sure to set the ws port different for each instance.

**Comment by rbish** [comment]
That did not seem to work to get rid of screen flashing

**Comment by sloaleks** [comment]
Just pointed to the wiki in case you didn't catch that.
