### ISSUE TITLE
In the Linux Installation wiki a further set of instructions informing people how to create a daemon is necesary

### ISSUE THREAD

**Issue by kinnth** [GuntharDeNiro/BTCT#350]
I followed the linux guide and got the bot up and running, however, it only runs while my terminal connection is up.  This is no good for the bot as it needs to run 24/7.

I am not familiar with linux, but I feel creating the bot as a daemon so that it can be run as a service is a necessary usecase.  I feel it would be a very worthwhile addition to make this easier with systemd so that it can be executed on multiple environments. 

If I can find out how to do it I will post my answer here so that it might then be shared on the wiki for others.

**Comment by vicdr** [comment]
I had the same problem...

Installed a program that enables use of "pm2 start file-name" to start the bot...

Follow this guide ... easy as.

[http://www.nikola-breznjak.com/blog/javascript/nodejs/using-pm2-to-run-your-node-js-apps-like-a-pro/](url)

**Comment by magicdude4eva** [comment]
To run Gunbot as a daemon (adjust path as required) - this is for RaspberryPi, under "regular Linux" you will find the service files in `/etc/systemd/system`

sudo vi /lib/systemd/system/gunbot.service
```
[Unit]
Description=GunBot Service
After=network.target remote-fs.target nss-lookup.target
 
[Service]
User=pi
Group=pi
Type=simple
WorkingDirectory=/home/pi/gunbot/GunbotArm
#ExecStart=/home/pi/gunbot/GunbotArm/gunthy-gui-arm
ExecStart=/home/pi/gunbot/GunbotArm/gunthy-arm
ExecStop=/usr/bin/kill \$(/run/gunbot.pid)
PIDFile=/run/gunbot.pid
Restart=on-abort
 
[Install]
WantedBy=multi-user.target
```

And then enable/start the service:
```
sudo chmod 644 /lib/systemd/system/gunbot.service
sudo systemctl daemon-reload
sudo systemctl enable gunbot.service
sudo systemctl start gunbot.service
sudo systemctl status gunbot.service
```

I don't particularly like this, as Gunbot does not write to a log-file and systemd strips out any colors. So pretty pointless in my opinion.

I have for now reverted to using an alias in .bashrc which will re-attach to an existing screen:
```
### Various aliases
alias gbs="cd /home/pi/gunbot/GunbotArm; screen -S "GunBot" -d -R /home/pi/gunbot/GunbotArm/gunthy-arm"
alias gbl="tail -f /home/pi/gunbot/GunbotArm/screenlog.log"
```
Create a .screenrc file via vi ~/.screenrc:
```
# Always show a status line in the window footer
hardstatus on
hardstatus alwayslastline
hardstatus string "%{.bW}%-w%{.rW}%n %t%{-}%+w %=%{..G} %H %{..Y} %m/%d %C%a "

# Autodetach session on hangup instead of
# terminating screen completely
autodetach on

# Turn off the splash screen
startup_message off

# set log on all windows
deflog on

# Log to ~/.screen/logs.
logfile "/home/pi/gunbot/GunbotArm/screenlog.log"
```

You can then just type in `gbs` to re-attach to the screen or `gbl` to view the log. This unfortunately does not survive a reboot. 

I hope that @GuntharDeNiro can provide some clarity if there are specific command line-arguments we can pass when running via systemd so that there is a log file written.

**Comment by HW-Peter** [comment]
Hey @magicdude4eva 

Your systemd script will work, you can simply grab the output by running

journalctl --unit=gunbot

Or if your like me and like to tail your logs

journalctl -f --unit=gunbot


Hope this helps

**Comment by magicdude4eva** [comment]
Thanks @HW-Peter - I have subsequently moved to supervisord where I can specify output for stdout/stderr. This works much better than systemd in my case.

The supervisord setup would be similar to the one I have here: https://gist.github.com/magicdude4eva/b910562342d2085ece184e09345b8685

**Comment by mobiledan121** [comment]
Big thanks to @magicdude4eva  @HW-Peter for making my day once I read this post
