### ISSUE TITLE
Does anyone know what this means?ema1 -\ Error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by mikebussy3334** [GuntharDeNiro/BTCT#40]
does anyone know how to fix this? or what it means.   

 ɢƱÑƁ۝Ŧ v4.0.4  Tips&Tricks: BTC-ZCL can be bought!!!
2017/08/17 13:14:32: There are some trading opportunities for BTC-ZCL at bittrex. Scanning Trade History
2017/08/17 13:14:32: Last Bid price BTC-ZCL: 0.00032018 | Last Ask: 0.00033088
2017/08/17 13:14:32: Balance BTC: 0.17212186
2017/08/17 13:14:32: Balance ZCL: 1.7148993
2017/08/17 13:14:32: On Orders ZCL: 0
Processing strategy BB for BTC-ZCL on bittrex
Error on strategy BB for BTC-ZCL on bittrex while getting ema1 -\ Error: Cannot read property '0' of null
------------------------------------------------------------------------------------------------
 ɢƱͶɮʘŁ v4.0.4  Scanning bittrex for trading opportunities 2017/08/17 13:14:32
------------------------------------------------------------------------------------------------

**Comment by MrG4dget** [comment]
+1

**Comment by kivo360** [comment]
+1 It's from the bb strategy for me

**Comment by eduard-shavyrko** [comment]
+1

**Comment by fahrmairm** [comment]
+1 
to add some info: for me this "Cannot read property '0' of null" happens only on bittrex but happens for any pair each and every time "Processing strategy BB for ..." appears. I let it run for a few minutes and nothing changed so to me it seems 4.0.3+ versions do not work on bittrex at all.

on poloniex I get "ema2 -/  Error: undefined is not a function" but only occasionally. The bot seems at least partially working since it buys and sells with profit, but my feeling is that it misses out some opportunities due to this error. However this observation might not be valid since I compare 4.0.4 poloniex vs. 3.3 on bittrex with only 80% pairs overlap.

**Comment by GuntharDeNiro** [comment]
fixed in v4.0.5
