### ISSUE TITLE
[BUG]Gunbot is not buying in Binance anymore

### ISSUE THREAD

**Issue by lazyghost77** [GuntharDeNiro/BTCT#410]
I have free 0.03 BITCOIN and trade limit is 0.002. Binance is not buying anything and gives this error. Same goes with DU. First DU buy doesn't happen on none of coins! I already registered this issue but gunthy without digging into the problem closed it. There is not issues with this in Bittrex.
![image](https://user-images.githubusercontent.com/25801048/34760379-517c3f26-f5e8-11e7-80ae-8573553b4bb1.png)

**Comment by yashspatel23** [comment]
**Explanation:**
Per the logs, Binance imposes a rule that quantity step sizes for POWR has to be divisible by 1.0000 with no remainder amount. The bot is asking to buy 20.1918 POWR at 0.00009905 to meet the 0.002 minimum trade limit but volume is being rounded down to 20 resulting in actual order value to be 0.001981 instead of 0.002. 

**Solution:**
In your config.js file, if you increase the TRADE_LIMIT from 0.002 to something a little higher, the issue will no longer occur.

**Comment by lazyghost77** [comment]
It worked 2 days ago. Bittrex doesnt have these problems. I don't want to increase to 0.003 because i don't have enough BTC for all pairs!

**Comment by yashspatel23** [comment]
Each exchange has different requirements. Bittrex does not enforce stepsize and so it can work just fine there. 

You can specify a manual override for the specific trading pair so that other pairs aren't affected. You don't have to set to 0.003, you should theoretically be able to do 0.0025 or whatever amount.

**Comment by lazyghost77** [comment]
Ok. Increased limit by 5000 SATS. Looks like working now and looks like Binance have increased min limit to 0.002 BTC. 6 months ago it was 0.001. It would be nice that GB had proper exception handling for this one.
