### ISSUE TITLE
Bot does not respect Binance HTTP 429

### ISSUE THREAD

**Issue by BobWatson** [GuntharDeNiro/BTCT#427]
The bot doesn't respect HTTP 429 from Binance - and instead of backing off / slowing down, keeps going and gets itself temp-banned.

**Comment by lazyghost77** [comment]
The same

**Comment by myn** [comment]
Can confirm this began this morning when Binance changed their API limits:

* GET /api/v1/aggTrades weight changed to 2
  * GET /api/v1/klines weight changed to 2
  * GET /api/v3/order weight changed to 2
  * GET /api/v3/allOrders weight changed to 20
  * GET /api/v3/account weight changed to 20
  * GET /api/v3/myTrades weight changed to 20
  * GET /api/v3/historicalTrades weight changed to 20

More info on Binance's github:  https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by myn** [comment]
Workaround is change BOT_DELAY from the default of 1 to 2.

**Comment by lazyghost77** [comment]
how many bots and how big is your poll rate?

**Comment by myn** [comment]
1 bot, 13 pairs. When you say "Poll Rate", are you refering to BOT_DELAY?  If so my BOT_DELAY is default at 1

**Comment by lazyghost77** [comment]
I was talking about "interval_ticker_update": 25000 parameter.  If it's one bot pair count wont matter. I ran 8 bots with 4 pairs each till today. Now I can't find the middle ground. The problem is that GB right ignores 429, and there is no other way to make it work faster than using only one bot and increasing delay.

**Comment by orkenstein** [comment]
Can anyone confirm, that Binance sends 429 at all?

**Comment by lazyghost77** [comment]
You cannot see it because GB doesn't show it in the log. You just get temp banned at one moment and there is no way to fix that other than increasing the bot delay which makes the bot pointless because it is too slow to go through all pairs.

**Comment by orkenstein** [comment]
@lazyghost77 i'm trying with my own python implementation, and see only 418. No 429.

**Comment by orkenstein** [comment]
From Binance API Telegram Channel:
>This is a known "issue/problem" and it is being worked on as @Ninj0r mentioned it a while ago @orkenstein

**Comment by claymore008** [comment]
> i'm trying with my own python implementation, and see only 418. No 429.<

Yes, because you guys have to read from "Public Rest API for Binance" this [https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits](url).

> HTTP 429 return code is used when breaking a request rate limit.
> HTTP 418 return code is used when an IP has been auto-banned for continuing to send requests after receiving 429 codes.

- > When a 429 is recieved, it's your obligation as an API to back off and not spam the API.
- > Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (http status 418).
- > IP bans are tracked and scale in duration for repeat offenders, from 2 minutes to 3 days.

**Comment by orkenstein** [comment]
@claymore008, yes. And I get no 429 at all.
