### ISSUE TITLE
[P0 BUG] Gross Miscalculation of P/L from Previous Buy

### ISSUE THREAD

**Issue by joemccann** [GuntharDeNiro/BTCT#446]
I recently upgraded from v6 to 7.0.2 with a fresh install, on a brand new EC2 instance.

The issue is I have a position in PPC-BTC on Poloniex which is "in the money" at the moment yet Gunbot is not selling.  It says that the last trade P&L was -30.09%, but if you view the buys and the current price you can see clearly that I am on the positive side, not negative.

The current price of PPC-BTC at the time of this posting is .00050451 BTC.

<img width="754" alt="screen shot 2018-01-21 at 08 05 39" src="https://user-images.githubusercontent.com/48234/35196110-948dacf8-fe82-11e7-8b5a-02bda0b4cca8.png">

<img width="1397" alt="screen shot 2018-01-21 at 08 06 29" src="https://user-images.githubusercontent.com/48234/35196112-9a6f0f90-fe82-11e7-8106-a3e6610cd0f3.png">

If the current price is .0005041 BTC and you see the purchases are .000486 then how is the calculation -30.09%?

**Comment by LetoAtre** [comment]
Same issue here on Binance

**Comment by GTrannoy** [comment]
Same behavior. Gunbot Last trade P/L stuck in same values for each pairs and GB is not selling anymore.

Related behavior I observed yesterday. Gunbot placed many orders until reaching my FUNDS_RESERVE.

So It is a problem because it sucks all my funds for one pair. I believed that TRADING_LIMIT concerned all authorized amount for one pair and not for one buy shot.

![xvg_behavior](https://user-images.githubusercontent.com/12541742/35214125-67134632-ff60-11e7-8c9e-3992d7ae1ea7.jpg)

**Comment by GTrannoy** [comment]
I believe the problem is a difference between chart on Binance and parameters into Gunbot strategies.

By example in binance, this is a parameter called 'bands: period' at left top for 'boll' curves.
I think it is equivalent to 'SMAPERIOD' but i am not sure. When I set '21' as in Binance and the curves for a pair is clearly in the upper band, the Bollinger Bands startegie doesn't detect it and doesn't change status to 'sell'.

I see that the next version of Gunbot would include the preview charts for Binance and I hope it could help to really see what is happening.

**Comment by ddey94** [comment]
Can confirm this also happens to me on Binance using emotionless Strat

all the trades in this pic have been confirmed positive by manual calculation, yet it shows negative P/L

![screen shot 2018-01-25 at 1 12 21 am](https://user-images.githubusercontent.com/34409894/35373567-08bc28ba-016d-11e8-8507-3b8a066a6d2a.png)
