### ISSUE TITLE
GB selling only partial amounts on Bitfinex

### ISSUE THREAD

**Issue by Tungsten183** [GuntharDeNiro/BTCT#543]
On each sell GB rounds down the amount to sell.
I had several cases where I bought 11 coins (balance then was 10.989 because of fees) and then later only sold 10 coins and I was left with 0.989.

from the logs:

"orders": {
    "0": {
      "time": 1524839583000,
      "type": "sell",
      "rate": 16.83,
      "amount": 10,
      "fees": 0.16829999999999998,
      "baseValue": 168.1317,
      "costProceed": 168.1317
    },
    "1": {
      "time": 1524808333000,
      "type": "buy",
      "rate": 15.1,
      "amount": 11,
      "fees": 0.1661,
      "baseValue": 166.2661,
      "costProceed": -166.2661
    }
  },
----

Thx

**Comment by datadecipher** [comment]
Same Here. It is selling partial amounts. Using the latest release.

**Comment by GuntharDeNiro** [comment]
orders get canceled when partially filled, until MIN_VOLUME_TO_SELL is match. This is on purpose to prevent unfilled orders stuck at order book. You can handle this with cancel orders setting in your config.js

**Comment by datadecipher** [comment]
No Gunthy, it is not due to that setting. Bot is placing orders by rounding off. For example - 
Bot Buys NEO, Amount - 1.985878
A sell order of Amount - 1.9 is placed. If it gets filled then 0.085878 amount is left.

Now bot gets stuck because bitfinex won't let it sell this small amount. Also, now bot assumes that it is in selling mode and it doesn't places a buy order when conditions are met.

**Comment by datadecipher** [comment]
It is happening with all the currencies on bitfinex.

**Comment by Tungsten183** [comment]
As datadecipher said. Its happening with all pairs I have tested so far. It always rounds down with putting up orders.

**Comment by GuntharDeNiro** [comment]
alright I have assigned this issue to our exchanges clerk the super awesome Yashie. Thanks for reporting
