### ISSUE TITLE
Error on 4.0.5

### ISSUE THREAD

**Issue by brandontsh** [GuntharDeNiro/BTCT#56]
Suddenly stopped working and got this error msg:

> Error on strategy BB_STEPGAIN for BTC-NEO on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined

**Comment by mikebussy3334** [comment]
BBSTEPGAIN omit the "_"

**Comment by brandontsh** [comment]
There is none in config files, it was working properly

**Comment by samcus** [comment]
@brandontsh Getting the same error but with BB, what did you have to do?

**Comment by GuntharDeNiro** [comment]
acknowledged
Thanks!

**Comment by GuntharDeNiro** [comment]
fixed in v5
Thanks for reporting this!

**Comment by miwi-fbsd** [comment]
Can we reopen this plz, its not fixed in 5.0.4

------------------------------------------------------------------------------------------------
 ɢՍҊɃ๏ͳ v5.0.4  Scanning bittrex for trading opportunities 2017/10/11 08:46:01
------------------------------------------------------------------------------------------------
2017/10/11 08:46:01: BTC-PPC Last Bid/Ask 0.00026900/0.00027391
Error on strategy BB_STEPGAIN for BTC-PPC on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined
------------------------------------------------------------------------------------------------
 ɢƱƝɃØŁ v5.0.4  Scanning bittrex for trading opportunities 2017/10/11 08:46:02
------------------------------------------------------------------------------------------------
2017/10/11 08:46:02: ETH-ZEC Last Bid/Ask 0.77964914/0.79237986
Error on strategy BB_STEPGAIN for ETH-ZEC on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined
------------------------------------------------------------------------------------------------
 ɢƱÑƁ๏ͳ v5.0.4  Scanning bittrex for trading opportunities 2017/10/11 08:46:03
------------------------------------------------------------------------------------------------
2017/10/11 08:46:03: BTC-DOPE Last Bid/Ask 0.00000602/0.00000610
Error on strategy BB_STEPGAIN for BTC-DOPE on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined
------------------------------------------------------------------------------------------------
 ɢƱͶƁǾͳ v5.0.4  Scanning bittrex for trading opportunities 2017/10/11 08:46:03
------------------------------------------------------------------------------------------------
2017/10/11 08:46:04: BTC-ZEC Last Bid/Ask 0.04920039/0.04949830
Error on strategy BB_STEPGAIN for BTC-ZEC on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined
------------------------------------------------------------------------------------------------
 ɢƱΠß๏ͳ v5.0.4  Scanning bittrex for trading opportunities 2017/10/11 08:46:05
------------------------------------------------------------------------------------------------
2017/10/11 08:46:05: BTC-NXC Last Bid/Ask 0.00004076/0.00004145
Error on strategy BB_STEPGAIN for BTC-NXC on bittrex while getting balances -| Error: TypeError: Cannot read property 'Available' of undefined
----------------------------------------------------------------------------------------

example config:

 "BTC-ZEC": {
                "override": {
                    "BUY_ENABLED": false
                },
                "strategy": "bbstepgain"
            },
            "ETH-XLM": {
                "override": {
                    "BUY_ENABLED": false
                },
                "strategy": "bbstepgain"
            },
            "BTC-NAV": {
                "override": {
                    "BUY_ENABLED": false
                },


        "bbstepgain": {
            "EMA1": 16,
            "DOUBLE_UP": true,
            "EMA2": 8,
            "HIGH_BB": 45,
            "MIN_VOLUME_TO_BUY": 0.001,
            "STOP_LIMIT": 60,
            "LOW_BB": 40,
            "MIN_VOLUME_TO_SELL": 0.001,
            "SELLLVL": 2,
            "SMAPERIOD": 20,
            "PERIOD": 5,
            "SELLLVL2": 3,
            "SELLLVL3": 70,
            "SELLLVL1": 0.6,
            "AVGPOINTS": 250,
            "AVGMINIMUM": 1e-08,
            "BUY_ENABLED": false,
            "BTC_TRADING_LIMIT": 0.001,
            "STDV": 2,
            "PANIC_SELL": false,
            "LASTPOINTS": 5
        },

**Comment by miwi-fbsd** [comment]
Ok Problem found,

thats happend when you mix BTC-X with ETH-X in one instance, as example we have 3 instances btc, eth , bags, so when we shift from btc and eth bags over to the bags instance it starts breaking the bot, seems like eth and btc cant be in the same instance.

not sure if that can be fixed :)
