### ISSUE TITLE
Not buying back after price increase

### ISSUE THREAD

**Issue by blackcell06** [GuntharDeNiro/BTCT#581]
Bot not buying back after RT price increase. 
![capture](https://user-images.githubusercontent.com/29755389/40152033-0cff760a-5949-11e8-9c14-3341ff2a43f7.PNG)

**Comment by blackcell06** [comment]
[binance-ETH-XLM-state.zip](https://github.com/GuntharDeNiro/BTCT/files/2011334/binance-ETH-XLM-state.zip)

**Comment by karenmkrohn** [comment]
I have experienced many similar instances, except that in a number of those cases, when the price rose high enough after that sell, the bot DID buy back at a price which appeared (visually, going by the charts, not calculated to confirm) to approximate the previous average bought price.  If this is indeed how the bot chooses when to buy back, then I find this unacceptable.  We need the bot to buy back at a user-configurable x% over that sell price which will be a *lower* price than the previous average bought price.    We also need to be able to tell the bot to abort the RT cycle entirely if it is unable to buy back at that specified lower price.  I have turned off RT because I feel that, as currently programmed, it has the bot rebuying at unnecessarily high prices.  I too would have expected the bot to rebuy just before that small peak which occurred after the sell in blackcell06's chart, shown above.

**Comment by blackcell06** [comment]
I just had that with BNB :( it bought back at a crazy high price

**Comment by Majestic81** [comment]
Same as
https://github.com/GuntharDeNiro/BTCT/issues/563

**Comment by alton-turner** [comment]
RT Not working as expected, have lost a lot of money on this, I have now had to stop using it.
![image](https://user-images.githubusercontent.com/34540631/41200115-456003b6-6cd1-11e8-8e16-516861d27212.png)
