### ISSUE TITLE
Unable to use Binance

### ISSUE THREAD

**Issue by JustinLangendoen** [GuntharDeNiro/BTCT#677]
Getting the following error when adding: BTC-ETH pair. Please help

Error: {}
    at errorHandler (C:\snapshot\gunbotv11public\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unable to connect to binance
Please if this error persists, stop Gunbot, wait a few minutes and then start it again...

**Comment by SupaaHiro** [comment]
I'm facing the same issue with both the versions v11.7.6 and v10.7.2.

On Windows 10, with a fresh/clean config that have just one pair USDT-BTC @ Binance and all default configurations, I get:
Unable to connect to binance @ v11.7.6
Error: Response code 401 / Unable to connect to binance @  v10.7.2
On Ubuntu 18.04.1 LTS I get the same error (but I only tried v11.7.6)

- My API and secrets are correct (ReadData enabled, Trading enabled, I tested the comunication with a simple nodeJs app)
- My time is synced with timesynctool (0.nettime.pool.ntp.org)
- I've disabled any firewall or antivirus during any attempt
- Funds are OK (both USDT and BTC)

I think is something related with the last binance API update (2018-11-13)

Any help is appreciated. Thanks in advance.

**Comment by dainius585** [comment]
I had the same error, fixed it. My pairs where wrong LTC-BNB instead of BNB-LTC.

**Comment by DrStrike** [comment]
I'm Getting this error and its the first time im trying to load.  Does the bot not connect if you dont have enough funds?  Sorry Im new... 

Loading config...
GUI Server Deployed: http://localhost:5000
Loading exchange - gdax
Loading data....
Error: {}
    at errorHandler (C:\snapshot\gunbotv11public\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unable to connect to gdax

**Comment by Qwatton** [comment]
The most common fix to the unable to connect to exchange issue is that the pairs you're attempting to trade are input incorrectly, although on the exchange the pairs may appear as 'BTC-USDT' or 'ETH-USDT' if you want to use USDT as your main base currency you will need to input them into Gunbot as 'USDT-BTC' or 'USDT-ETH' @justinLangendoen, I can only assume that you're trying to use Ethereum as your base currency and that you've input the pair as 'BTC-ETH' instead of 'ETH-BTC' @DrStrike, no the bot will not function if you do not have enough currency to trade, of course. Changing the 'trading_limit' setting in the Gunbot GUI will change how much the bot uses for each trade, worked out in your base currency. Alternatively you can use the percentage option to use a percentage of your total amount of base currency. This is explained better on the Gunbot Wiki GitHub but I hope this helps a bit at least.

**Comment by DrStrike** [comment]
Thanks for the help thus far, Im still getting the below error, I've been trying different pairs forwards and backwards and also tried the balance trading limit to "All-In " in a attempt to get it to connect.  

Any Thoughts?

Loading data....
Error: {}
    at errorHandler (C:\snapshot\gunbotv11public\ctx-wrapper.js:0:0)
    at  <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unable to connect to gdax
Please if this error persists, stop Gunbot, wait a few minutes and then start it again...

**Comment by grumpy-kitty** [comment]
Update to the latest version.
