### ISSUE TITLE
Bot doesn't examine existing open BUY orders

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#73]
Please explain what happened here. Why did the bot place so many buy orders? Only happened on this on pair out of 30 last night.

Clearly the bot is not paying attention to existing BUY orders.

![screen shot 2017-09-04 at 9 16 08 am](https://user-images.githubusercontent.com/4413670/30030302-4beb26da-9152-11e7-8b45-f8a9f2e6f60c.png)

```
"BTC_DOGE":  { "strategy": "stepgain", "override": { "MIN_VOLUME_TO_SELL": 1000.0 } },
...
"bot": {
                "debug": true,
                "period_storage_ticker": 1000,
                "interval_ticker_update": 25000,
                "timeout_buy": 60000,
                "timeout_sell": 60000,
                "WATCH_MODE": false,
                "VERBOSE": true
        },
                "stepgain": {
			"BTC_TRADING_LIMIT": 0.01,
                        "PERIOD": 15,
                        "BUYLVL1": 1.5,
                        "BUYLVL2": 1.8,
                        "BUYLVL3": 70,
                        "SELLLVL1": 1.5,
                        "SELLLVL2": 1.6,
                  	"SELLLVL3": 70,
                        "BUYLVL": 2,
                        "SELLLVL": 2,
                        "LASTPOINTS": 15,
                        "AVGPOINTS": 100,
                        "AVGMINIMUM": 0.00000001,
                        "EMA1": 16,
                        "EMA2": 8,
                        "PANIC_SELL": false,
       	       	       	"DOUBLE_UP": false,
                        "STOP_LIMIT": 999,
                        "BUY_ENABLED": true,
                        "MIN_VOLUME_TO_BUY": 0.001,
                        "MIN_VOLUME_TO_SELL": 0.001
                },
```

**Comment by GuntharDeNiro** [comment]
attempting to debug this since long time: it happens only on some shitcoins. I'll attempt to put some more checks for this before so send buy order. Actually we filter for the following:
- if we have already altcoin balance, we dont buy
- if we have already sent a buy order and it is still unfilled, we dont buy
- if at least 120 seconds from latest timestamp a pair was processed, we dont process it again

I am really puzzled about the reason why this is still happening. I'll investigate more.
PS: reference to#76 is invalid

**Comment by utdrmac** [comment]
Thanks for looking. I removed the reference.

**Comment by GuntharDeNiro** [comment]
fixed in v5
Thanks for reporting this!
