### ISSUE TITLE
Wrong BB settings in 5.0.1

### ISSUE THREAD

**Issue by peppoonline** [GuntharDeNiro/BTCT#84]
I get wrong results with BB strategy. It tells me that the lowBB and highBB are the same values.
And in result of that it buys/sells in strange ways (so it's not just a display bug).
It happens with or without the Gunbot GUI from Sjakil.

Standard settings:

		"bb": {
			"BTC_TRADING_LIMIT": 0.008,
			"PERIOD": 15,
			"EMA1": 200,
			"EMA2": 50,
			"GAIN": 2,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": false,
			"MIN_VOLUME_TO_BUY": 0.0005,
			"MIN_VOLUME_TO_SELL": 0.0005

Example1

![image](https://user-images.githubusercontent.com/31846019/30267389-ae79373e-96e2-11e7-90ee-72ec8311ca5d.png)

Example2
![image](https://user-images.githubusercontent.com/31846019/30267403-bd3b86f0-96e2-11e7-9fb0-649b122ba1fe.png)

**Comment by dechut** [comment]
same problem .
im running bbstepgain , bblow is 25 , but my bot buy with very higher than bblow 25

marked is buy zone .

![image](https://user-images.githubusercontent.com/31846587/30267972-694827d4-970e-11e7-94a2-9c585a7c9c83.png)

**Comment by GuntharDeNiro** [comment]
not a bug: you actually need to play with all settings to build up BB. I included everything in this version: period_storage_tickers, STDV, SMAPERIOD.

**Comment by murm78** [comment]
What do you mean you need to play with all the settings? Won't the default settings build a BB like poloniex does by default?

This isn't just because the bot needed time to collect more data for its calculations to become accurate?

**Comment by arnthorsnaer** [comment]
@GuntharDeNiro  How should I play with all settings to build up BB? Can you explain or point me in the direction of docs where I can explore this?

**Comment by TenaciousJai** [comment]
Without knowing how the bot calculates the BB precisely, there is no way to know how changing settings will affect its buy/sell orders.  Posting the formula used to calculate it would be helpful, and will save people money and time spent fiddling with settings blindly.

**Comment by lenardbang** [comment]
I would also like to know this about BB calc, when i changed strategy to bbstepgain, on few coins HIGH BB = SMA = LOW BB, those coins were bought right away, with LOW BB set to 5 (which is ok, since all HIH/LOW/SMA are the same). Question is WHY are they the same? I would assume default settings provided with the bot wouldnt require any 'changes' for BB values to be calculated properly....

**Comment by BitFlipp3r** [comment]
Seriously, we are trading with real money here so "play with all settings" is not the answer we are looking for. I understand that you might want people to pay for the GBU to get the best settings, but this absolute secrecy just makes people stop using the bot. The short comments behind every parameter is not enough to understand how they affect the algorithms.

**Comment by GuntharDeNiro** [comment]
@BitFlipp3r whoever of you wrote this is a retard

**Comment by TenaciousJai** [comment]
You're not winning any friends here G.  Not after we paid upwards of $400 for your software.  We expect it to be supported properly - this isn't some free github code we're downloading to beta test.

**Comment by GuntharDeNiro** [comment]
@TenaciousJai BETA release: dont use it. Send me your addy as i refund you too.

**Comment by TenaciousJai** [comment]
This was not released as a beta, nowhere on the announcement do you inform anyone that 5.0.1 is beta software, and I'll gladly accept a refund sir.  Autoview extension is 1/10th the price of Gunbot, can do the exact same functions directly from tradingview, and you don't have to pay an extra 50% for the privilege.

Not only does your product NOT WORK properly, but you arrogantly claim that anyone suggesting your code might be flawed MUST be wrong since you are such an infallible programmer.  Your code doesn't work right.  I've seen it over and over.  I've posted pictures of it NOT working right on your forums.  I would be happy to do so again just to prove a point.

In the future, you should really reconsider your attitude toward your paying customers.  Calling them retards for asking legitimate questions is improper behavior for an adult, particularly one trying charging customers for a product.  You're not the fucking soup nazi.

**Comment by GuntharDeNiro** [comment]
* Middle Band = 20-day simple moving average (SMA)
  * Upper Band = 20-day SMA + (20-day standard deviation of price x 2) 
  * Lower Band = 20-day SMA - (20-day standard deviation of price x 2)
This is the BB formula
In config.js you have all variables to set
The problem is some coins have a price variation in a short time frame while others with low volume, have a price variation with longer time frame. So, i.e. you would collect an array of similar prices (or equal price) for BELA in 5 minutes, while you would get a bigger vairance of prices in 5 minutes for ETH
Suggestions: make interval ticker update longer than 25 seconds, it wont affect trades

**Comment by TenaciousJai** [comment]
Censorship eh... figures.

**Comment by murm78** [comment]
> make interval ticker update longer than 25 seconds, it wont affect trades

It won't affect trades even on the coins that have a lot of price variation in a short time frame??
